//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinStat.AnalizeUI.StatisticDataReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatisticData", Namespace="http://schemas.datacontract.org/2004/07/MinStat.DAL.POCO.ResultItems")]
    [System.SerializableAttribute()]
    public partial class StatisticData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private MinStat.AnalizeUI.StatisticDataReference.StatisticDataItem[] Linesk__BackingFieldField;
        
        private System.Collections.Generic.Dictionary<string, string> Titlesk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Lines>k__BackingField", IsRequired=true)]
        public MinStat.AnalizeUI.StatisticDataReference.StatisticDataItem[] Linesk__BackingField {
            get {
                return this.Linesk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Linesk__BackingFieldField, value) != true)) {
                    this.Linesk__BackingFieldField = value;
                    this.RaisePropertyChanged("Linesk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Titles>k__BackingField", IsRequired=true)]
        public System.Collections.Generic.Dictionary<string, string> Titlesk__BackingField {
            get {
                return this.Titlesk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Titlesk__BackingFieldField, value) != true)) {
                    this.Titlesk__BackingFieldField = value;
                    this.RaisePropertyChanged("Titlesk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatisticDataItem", Namespace="http://schemas.datacontract.org/2004/07/MinStat.DAL.POCO.ResultItems")]
    [System.SerializableAttribute()]
    public partial class StatisticDataItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string Idk__BackingFieldField;
        
        private int StrongLevelk__BackingFieldField;
        
        private string Titlek__BackingFieldField;
        
        private string[] Valuesk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Id>k__BackingField", IsRequired=true)]
        public string Idk__BackingField {
            get {
                return this.Idk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Idk__BackingFieldField, value) != true)) {
                    this.Idk__BackingFieldField = value;
                    this.RaisePropertyChanged("Idk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<StrongLevel>k__BackingField", IsRequired=true)]
        public int StrongLevelk__BackingField {
            get {
                return this.StrongLevelk__BackingFieldField;
            }
            set {
                if ((this.StrongLevelk__BackingFieldField.Equals(value) != true)) {
                    this.StrongLevelk__BackingFieldField = value;
                    this.RaisePropertyChanged("StrongLevelk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Title>k__BackingField", IsRequired=true)]
        public string Titlek__BackingField {
            get {
                return this.Titlek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Titlek__BackingFieldField, value) != true)) {
                    this.Titlek__BackingFieldField = value;
                    this.RaisePropertyChanged("Titlek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Values>k__BackingField", IsRequired=true)]
        public string[] Valuesk__BackingField {
            get {
                return this.Valuesk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Valuesk__BackingFieldField, value) != true)) {
                    this.Valuesk__BackingFieldField = value;
                    this.RaisePropertyChanged("Valuesk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Activity", Namespace="http://schemas.datacontract.org/2004/07/MinStat.DAL.POCO")]
    [System.SerializableAttribute()]
    public partial class Activity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int Idk__BackingFieldField;
        
        private int Part_1k__BackingFieldField;
        
        private int Part_2k__BackingFieldField;
        
        private int Part_3k__BackingFieldField;
        
        private int Part_4k__BackingFieldField;
        
        private int Part_5k__BackingFieldField;
        
        private string Titlek__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Id>k__BackingField", IsRequired=true)]
        public int Idk__BackingField {
            get {
                return this.Idk__BackingFieldField;
            }
            set {
                if ((this.Idk__BackingFieldField.Equals(value) != true)) {
                    this.Idk__BackingFieldField = value;
                    this.RaisePropertyChanged("Idk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Part_1>k__BackingField", IsRequired=true)]
        public int Part_1k__BackingField {
            get {
                return this.Part_1k__BackingFieldField;
            }
            set {
                if ((this.Part_1k__BackingFieldField.Equals(value) != true)) {
                    this.Part_1k__BackingFieldField = value;
                    this.RaisePropertyChanged("Part_1k__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Part_2>k__BackingField", IsRequired=true)]
        public int Part_2k__BackingField {
            get {
                return this.Part_2k__BackingFieldField;
            }
            set {
                if ((this.Part_2k__BackingFieldField.Equals(value) != true)) {
                    this.Part_2k__BackingFieldField = value;
                    this.RaisePropertyChanged("Part_2k__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Part_3>k__BackingField", IsRequired=true)]
        public int Part_3k__BackingField {
            get {
                return this.Part_3k__BackingFieldField;
            }
            set {
                if ((this.Part_3k__BackingFieldField.Equals(value) != true)) {
                    this.Part_3k__BackingFieldField = value;
                    this.RaisePropertyChanged("Part_3k__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Part_4>k__BackingField", IsRequired=true)]
        public int Part_4k__BackingField {
            get {
                return this.Part_4k__BackingFieldField;
            }
            set {
                if ((this.Part_4k__BackingFieldField.Equals(value) != true)) {
                    this.Part_4k__BackingFieldField = value;
                    this.RaisePropertyChanged("Part_4k__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Part_5>k__BackingField", IsRequired=true)]
        public int Part_5k__BackingField {
            get {
                return this.Part_5k__BackingFieldField;
            }
            set {
                if ((this.Part_5k__BackingFieldField.Equals(value) != true)) {
                    this.Part_5k__BackingFieldField = value;
                    this.RaisePropertyChanged("Part_5k__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Title>k__BackingField", IsRequired=true)]
        public string Titlek__BackingField {
            get {
                return this.Titlek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Titlek__BackingFieldField, value) != true)) {
                    this.Titlek__BackingFieldField = value;
                    this.RaisePropertyChanged("Titlek__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FilterCritery", Namespace="http://schemas.datacontract.org/2004/07/MinStat.DAL.POCO")]
    [System.SerializableAttribute()]
    public partial class FilterCritery : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Collections.Generic.KeyValuePair<int, string> KeyField;
        
        private string KeyValueField;
        
        private System.Collections.Generic.Dictionary<int, string> Innerk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.KeyValuePair<int, string> Key {
            get {
                return this.KeyField;
            }
            set {
                if ((this.KeyField.Equals(value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string KeyValue {
            get {
                return this.KeyValueField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyValueField, value) != true)) {
                    this.KeyValueField = value;
                    this.RaisePropertyChanged("KeyValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Inner>k__BackingField", IsRequired=true)]
        public System.Collections.Generic.Dictionary<int, string> Innerk__BackingField {
            get {
                return this.Innerk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Innerk__BackingFieldField, value) != true)) {
                    this.Innerk__BackingFieldField = value;
                    this.RaisePropertyChanged("Innerk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.fem-sut.spb.ru/", ConfigurationName="StatisticDataReference.StatisticDataService")]
    public interface StatisticDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fem-sut.spb.ru/StatisticDataService/GetFullReport", ReplyAction="http://www.fem-sut.spb.ru/StatisticDataService/GetFullReportResponse")]
        MinStat.AnalizeUI.StatisticDataReference.StatisticData[] GetFullReport(int enterpriseId, int federalSubjectId, int federalDistrictId, System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fem-sut.spb.ru/StatisticDataService/GetStaticConsolidatedReport", ReplyAction="http://www.fem-sut.spb.ru/StatisticDataService/GetStaticConsolidatedReportRespons" +
            "e")]
        MinStat.AnalizeUI.StatisticDataReference.StatisticData[] GetStaticConsolidatedReport(int enterpriseId, int federalSubjectId, int federalDistrictId, System.DateTime startDate, System.DateTime endDate, int[] activities, int[] criteries);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fem-sut.spb.ru/StatisticDataService/GetDynamicConsolidatedReport", ReplyAction="http://www.fem-sut.spb.ru/StatisticDataService/GetDynamicConsolidatedReportRespon" +
            "se")]
        MinStat.AnalizeUI.StatisticDataReference.StatisticData[] GetDynamicConsolidatedReport(int enterpriseId, int federalSubjectId, int federalDistrictId, System.DateTime startDate, System.DateTime endDate, int[] activities, int[] criteries);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fem-sut.spb.ru/StatisticDataService/GetQtyStaticReport", ReplyAction="http://www.fem-sut.spb.ru/StatisticDataService/GetQtyStaticReportResponse")]
        MinStat.AnalizeUI.StatisticDataReference.StatisticData[] GetQtyStaticReport(int enterpriseId, int federalSubjectId, int federalDistrictId, System.DateTime startDate, System.DateTime endDate, int[] verticalChecks, System.Collections.Generic.KeyValuePair<int, int>[] horizontalChecks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fem-sut.spb.ru/StatisticDataService/GetQtyDynamicReport", ReplyAction="http://www.fem-sut.spb.ru/StatisticDataService/GetQtyDynamicReportResponse")]
        MinStat.AnalizeUI.StatisticDataReference.StatisticData[] GetQtyDynamicReport(int enterpriseId, int federalSubjectId, int federalDistrictId, System.DateTime startDate, System.DateTime endDate, int[] verticalChecks, System.Collections.Generic.KeyValuePair<int, int>[] horizontalChecks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fem-sut.spb.ru/StatisticDataService/GetSummaryReport", ReplyAction="http://www.fem-sut.spb.ru/StatisticDataService/GetSummaryReportResponse")]
        MinStat.AnalizeUI.StatisticDataReference.StatisticData[] GetSummaryReport(int enterpiseId, int federalSubjectId, int federalDistrictId, System.DateTime boundDate, int[] activities, int[] genders, int[] educationLevels, int[] postLevels);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fem-sut.spb.ru/StatisticDataService/GetFederalDistricts", ReplyAction="http://www.fem-sut.spb.ru/StatisticDataService/GetFederalDistrictsResponse")]
        System.Collections.Generic.Dictionary<int, string> GetFederalDistricts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fem-sut.spb.ru/StatisticDataService/GetFederalSubjects", ReplyAction="http://www.fem-sut.spb.ru/StatisticDataService/GetFederalSubjectsResponse")]
        System.Collections.Generic.Dictionary<int, string> GetFederalSubjects(int districtId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fem-sut.spb.ru/StatisticDataService/GetEnterprises", ReplyAction="http://www.fem-sut.spb.ru/StatisticDataService/GetEnterprisesResponse")]
        System.Collections.Generic.Dictionary<int, string> GetEnterprises(int subjectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fem-sut.spb.ru/StatisticDataService/GetActivities", ReplyAction="http://www.fem-sut.spb.ru/StatisticDataService/GetActivitiesResponse")]
        MinStat.AnalizeUI.StatisticDataReference.Activity[] GetActivities();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fem-sut.spb.ru/StatisticDataService/GetConsolidateFilterCritery", ReplyAction="http://www.fem-sut.spb.ru/StatisticDataService/GetConsolidateFilterCriteryRespons" +
            "e")]
        MinStat.AnalizeUI.StatisticDataReference.FilterCritery[] GetConsolidateFilterCritery();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fem-sut.spb.ru/StatisticDataService/GetPostLevels", ReplyAction="http://www.fem-sut.spb.ru/StatisticDataService/GetPostLevelsResponse")]
        System.Collections.Generic.Dictionary<int, string> GetPostLevels();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fem-sut.spb.ru/StatisticDataService/GetEducationLevels", ReplyAction="http://www.fem-sut.spb.ru/StatisticDataService/GetEducationLevelsResponse")]
        System.Collections.Generic.Dictionary<int, string> GetEducationLevels();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StatisticDataServiceChannel : MinStat.AnalizeUI.StatisticDataReference.StatisticDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StatisticDataServiceClient : System.ServiceModel.ClientBase<MinStat.AnalizeUI.StatisticDataReference.StatisticDataService>, MinStat.AnalizeUI.StatisticDataReference.StatisticDataService {
        
        public StatisticDataServiceClient() {
        }
        
        public StatisticDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StatisticDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StatisticDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StatisticDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MinStat.AnalizeUI.StatisticDataReference.StatisticData[] GetFullReport(int enterpriseId, int federalSubjectId, int federalDistrictId, System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.GetFullReport(enterpriseId, federalSubjectId, federalDistrictId, startDate, endDate);
        }
        
        public MinStat.AnalizeUI.StatisticDataReference.StatisticData[] GetStaticConsolidatedReport(int enterpriseId, int federalSubjectId, int federalDistrictId, System.DateTime startDate, System.DateTime endDate, int[] activities, int[] criteries) {
            return base.Channel.GetStaticConsolidatedReport(enterpriseId, federalSubjectId, federalDistrictId, startDate, endDate, activities, criteries);
        }
        
        public MinStat.AnalizeUI.StatisticDataReference.StatisticData[] GetDynamicConsolidatedReport(int enterpriseId, int federalSubjectId, int federalDistrictId, System.DateTime startDate, System.DateTime endDate, int[] activities, int[] criteries) {
            return base.Channel.GetDynamicConsolidatedReport(enterpriseId, federalSubjectId, federalDistrictId, startDate, endDate, activities, criteries);
        }
        
        public MinStat.AnalizeUI.StatisticDataReference.StatisticData[] GetQtyStaticReport(int enterpriseId, int federalSubjectId, int federalDistrictId, System.DateTime startDate, System.DateTime endDate, int[] verticalChecks, System.Collections.Generic.KeyValuePair<int, int>[] horizontalChecks) {
            return base.Channel.GetQtyStaticReport(enterpriseId, federalSubjectId, federalDistrictId, startDate, endDate, verticalChecks, horizontalChecks);
        }
        
        public MinStat.AnalizeUI.StatisticDataReference.StatisticData[] GetQtyDynamicReport(int enterpriseId, int federalSubjectId, int federalDistrictId, System.DateTime startDate, System.DateTime endDate, int[] verticalChecks, System.Collections.Generic.KeyValuePair<int, int>[] horizontalChecks) {
            return base.Channel.GetQtyDynamicReport(enterpriseId, federalSubjectId, federalDistrictId, startDate, endDate, verticalChecks, horizontalChecks);
        }
        
        public MinStat.AnalizeUI.StatisticDataReference.StatisticData[] GetSummaryReport(int enterpiseId, int federalSubjectId, int federalDistrictId, System.DateTime boundDate, int[] activities, int[] genders, int[] educationLevels, int[] postLevels) {
            return base.Channel.GetSummaryReport(enterpiseId, federalSubjectId, federalDistrictId, boundDate, activities, genders, educationLevels, postLevels);
        }
        
        public System.Collections.Generic.Dictionary<int, string> GetFederalDistricts() {
            return base.Channel.GetFederalDistricts();
        }
        
        public System.Collections.Generic.Dictionary<int, string> GetFederalSubjects(int districtId) {
            return base.Channel.GetFederalSubjects(districtId);
        }
        
        public System.Collections.Generic.Dictionary<int, string> GetEnterprises(int subjectId) {
            return base.Channel.GetEnterprises(subjectId);
        }
        
        public MinStat.AnalizeUI.StatisticDataReference.Activity[] GetActivities() {
            return base.Channel.GetActivities();
        }
        
        public MinStat.AnalizeUI.StatisticDataReference.FilterCritery[] GetConsolidateFilterCritery() {
            return base.Channel.GetConsolidateFilterCritery();
        }
        
        public System.Collections.Generic.Dictionary<int, string> GetPostLevels() {
            return base.Channel.GetPostLevels();
        }
        
        public System.Collections.Generic.Dictionary<int, string> GetEducationLevels() {
            return base.Channel.GetEducationLevels();
        }
    }
}
