//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinStat.AnalizeUI.AdministrationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdministrationService.AdministrationService")]
    public interface AdministrationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdministrationService/CreateEnterprise", ReplyAction="http://tempuri.org/AdministrationService/CreateEnterpriseResponse")]
        void CreateEnterprise(string enterpriseTitle, int federalSubjectId, string mail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdministrationService/RemoveEnterprise", ReplyAction="http://tempuri.org/AdministrationService/RemoveEnterpriseResponse")]
        void RemoveEnterprise(int enterpriseId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AdministrationServiceChannel : MinStat.AnalizeUI.AdministrationService.AdministrationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdministrationServiceClient : System.ServiceModel.ClientBase<MinStat.AnalizeUI.AdministrationService.AdministrationService>, MinStat.AnalizeUI.AdministrationService.AdministrationService {
        
        public AdministrationServiceClient() {
        }
        
        public AdministrationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdministrationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdministrationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdministrationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CreateEnterprise(string enterpriseTitle, int federalSubjectId, string mail) {
            base.Channel.CreateEnterprise(enterpriseTitle, federalSubjectId, mail);
        }
        
        public void RemoveEnterprise(int enterpriseId) {
            base.Channel.RemoveEnterprise(enterpriseId);
        }
    }
}
