//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinStat.Enterprises.WebUI.EnterpriseServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Summary", Namespace="http://schemas.datacontract.org/2004/07/MinStat.Enterprises.DAL.POCO")]
    [System.SerializableAttribute()]
    public partial class Summary : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AuthorNamek__BackingFieldField;
        
        private System.DateTime CreateDatek__BackingFieldField;
        
        private int EnterpriseIdk__BackingFieldField;
        
        private int Idk__BackingFieldField;
        
        private System.DateTime PublishedDatek__BackingFieldField;
        
        private bool Publishedk__BackingFieldField;
        
        private MinStat.Enterprises.WebUI.EnterpriseServiceReference.SummaryActivity[] SummaryActivitiesk__BackingFieldField;
        
        private string Titlek__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<AuthorName>k__BackingField", IsRequired=true)]
        public string AuthorNamek__BackingField {
            get {
                return this.AuthorNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorNamek__BackingFieldField, value) != true)) {
                    this.AuthorNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("AuthorNamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CreateDate>k__BackingField", IsRequired=true)]
        public System.DateTime CreateDatek__BackingField {
            get {
                return this.CreateDatek__BackingFieldField;
            }
            set {
                if ((this.CreateDatek__BackingFieldField.Equals(value) != true)) {
                    this.CreateDatek__BackingFieldField = value;
                    this.RaisePropertyChanged("CreateDatek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<EnterpriseId>k__BackingField", IsRequired=true)]
        public int EnterpriseIdk__BackingField {
            get {
                return this.EnterpriseIdk__BackingFieldField;
            }
            set {
                if ((this.EnterpriseIdk__BackingFieldField.Equals(value) != true)) {
                    this.EnterpriseIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("EnterpriseIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Id>k__BackingField", IsRequired=true)]
        public int Idk__BackingField {
            get {
                return this.Idk__BackingFieldField;
            }
            set {
                if ((this.Idk__BackingFieldField.Equals(value) != true)) {
                    this.Idk__BackingFieldField = value;
                    this.RaisePropertyChanged("Idk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<PublishedDate>k__BackingField", IsRequired=true)]
        public System.DateTime PublishedDatek__BackingField {
            get {
                return this.PublishedDatek__BackingFieldField;
            }
            set {
                if ((this.PublishedDatek__BackingFieldField.Equals(value) != true)) {
                    this.PublishedDatek__BackingFieldField = value;
                    this.RaisePropertyChanged("PublishedDatek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Published>k__BackingField", IsRequired=true)]
        public bool Publishedk__BackingField {
            get {
                return this.Publishedk__BackingFieldField;
            }
            set {
                if ((this.Publishedk__BackingFieldField.Equals(value) != true)) {
                    this.Publishedk__BackingFieldField = value;
                    this.RaisePropertyChanged("Publishedk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<SummaryActivities>k__BackingField", IsRequired=true)]
        public MinStat.Enterprises.WebUI.EnterpriseServiceReference.SummaryActivity[] SummaryActivitiesk__BackingField {
            get {
                return this.SummaryActivitiesk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.SummaryActivitiesk__BackingFieldField, value) != true)) {
                    this.SummaryActivitiesk__BackingFieldField = value;
                    this.RaisePropertyChanged("SummaryActivitiesk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Title>k__BackingField", IsRequired=true)]
        public string Titlek__BackingField {
            get {
                return this.Titlek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Titlek__BackingFieldField, value) != true)) {
                    this.Titlek__BackingFieldField = value;
                    this.RaisePropertyChanged("Titlek__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SummaryActivity", Namespace="http://schemas.datacontract.org/2004/07/MinStat.Enterprises.DAL.POCO")]
    [System.SerializableAttribute()]
    public partial class SummaryActivity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ActivityIdk__BackingFieldField;
        
        private MinStat.Enterprises.WebUI.EnterpriseServiceReference.Activity Activityk__BackingFieldField;
        
        private int SummaryIdk__BackingFieldField;
        
        private MinStat.Enterprises.WebUI.EnterpriseServiceReference.Summary Summaryk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ActivityId>k__BackingField", IsRequired=true)]
        public int ActivityIdk__BackingField {
            get {
                return this.ActivityIdk__BackingFieldField;
            }
            set {
                if ((this.ActivityIdk__BackingFieldField.Equals(value) != true)) {
                    this.ActivityIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("ActivityIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Activity>k__BackingField", IsRequired=true)]
        public MinStat.Enterprises.WebUI.EnterpriseServiceReference.Activity Activityk__BackingField {
            get {
                return this.Activityk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Activityk__BackingFieldField, value) != true)) {
                    this.Activityk__BackingFieldField = value;
                    this.RaisePropertyChanged("Activityk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<SummaryId>k__BackingField", IsRequired=true)]
        public int SummaryIdk__BackingField {
            get {
                return this.SummaryIdk__BackingFieldField;
            }
            set {
                if ((this.SummaryIdk__BackingFieldField.Equals(value) != true)) {
                    this.SummaryIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("SummaryIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Summary>k__BackingField", IsRequired=true)]
        public MinStat.Enterprises.WebUI.EnterpriseServiceReference.Summary Summaryk__BackingField {
            get {
                return this.Summaryk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Summaryk__BackingFieldField, value) != true)) {
                    this.Summaryk__BackingFieldField = value;
                    this.RaisePropertyChanged("Summaryk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Activity", Namespace="http://schemas.datacontract.org/2004/07/MinStat.Enterprises.DAL.POCO")]
    [System.SerializableAttribute()]
    public partial class Activity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int Idk__BackingFieldField;
        
        private int Part_1k__BackingFieldField;
        
        private int Part_2k__BackingFieldField;
        
        private int Part_3k__BackingFieldField;
        
        private int Part_4k__BackingFieldField;
        
        private int Part_5k__BackingFieldField;
        
        private MinStat.Enterprises.WebUI.EnterpriseServiceReference.SummaryActivity[] SummaryActivitiesk__BackingFieldField;
        
        private string Titlek__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Id>k__BackingField", IsRequired=true)]
        public int Idk__BackingField {
            get {
                return this.Idk__BackingFieldField;
            }
            set {
                if ((this.Idk__BackingFieldField.Equals(value) != true)) {
                    this.Idk__BackingFieldField = value;
                    this.RaisePropertyChanged("Idk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Part_1>k__BackingField", IsRequired=true)]
        public int Part_1k__BackingField {
            get {
                return this.Part_1k__BackingFieldField;
            }
            set {
                if ((this.Part_1k__BackingFieldField.Equals(value) != true)) {
                    this.Part_1k__BackingFieldField = value;
                    this.RaisePropertyChanged("Part_1k__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Part_2>k__BackingField", IsRequired=true)]
        public int Part_2k__BackingField {
            get {
                return this.Part_2k__BackingFieldField;
            }
            set {
                if ((this.Part_2k__BackingFieldField.Equals(value) != true)) {
                    this.Part_2k__BackingFieldField = value;
                    this.RaisePropertyChanged("Part_2k__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Part_3>k__BackingField", IsRequired=true)]
        public int Part_3k__BackingField {
            get {
                return this.Part_3k__BackingFieldField;
            }
            set {
                if ((this.Part_3k__BackingFieldField.Equals(value) != true)) {
                    this.Part_3k__BackingFieldField = value;
                    this.RaisePropertyChanged("Part_3k__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Part_4>k__BackingField", IsRequired=true)]
        public int Part_4k__BackingField {
            get {
                return this.Part_4k__BackingFieldField;
            }
            set {
                if ((this.Part_4k__BackingFieldField.Equals(value) != true)) {
                    this.Part_4k__BackingFieldField = value;
                    this.RaisePropertyChanged("Part_4k__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Part_5>k__BackingField", IsRequired=true)]
        public int Part_5k__BackingField {
            get {
                return this.Part_5k__BackingFieldField;
            }
            set {
                if ((this.Part_5k__BackingFieldField.Equals(value) != true)) {
                    this.Part_5k__BackingFieldField = value;
                    this.RaisePropertyChanged("Part_5k__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<SummaryActivities>k__BackingField", IsRequired=true)]
        public MinStat.Enterprises.WebUI.EnterpriseServiceReference.SummaryActivity[] SummaryActivitiesk__BackingField {
            get {
                return this.SummaryActivitiesk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.SummaryActivitiesk__BackingFieldField, value) != true)) {
                    this.SummaryActivitiesk__BackingFieldField = value;
                    this.RaisePropertyChanged("SummaryActivitiesk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Title>k__BackingField", IsRequired=true)]
        public string Titlek__BackingField {
            get {
                return this.Titlek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Titlek__BackingFieldField, value) != true)) {
                    this.Titlek__BackingFieldField = value;
                    this.RaisePropertyChanged("Titlek__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/MinStat.Enterprises.DAL.POCO")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ActivityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BirthYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DismissalYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EducationLevelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HiringYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PostLevelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StartPostYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SummaryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool WasQualificationIncreaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool WasValidateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal YearSalaryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActivityId {
            get {
                return this.ActivityIdField;
            }
            set {
                if ((this.ActivityIdField.Equals(value) != true)) {
                    this.ActivityIdField = value;
                    this.RaisePropertyChanged("ActivityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BirthYear {
            get {
                return this.BirthYearField;
            }
            set {
                if ((this.BirthYearField.Equals(value) != true)) {
                    this.BirthYearField = value;
                    this.RaisePropertyChanged("BirthYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DismissalYear {
            get {
                return this.DismissalYearField;
            }
            set {
                if ((this.DismissalYearField.Equals(value) != true)) {
                    this.DismissalYearField = value;
                    this.RaisePropertyChanged("DismissalYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EducationLevelId {
            get {
                return this.EducationLevelIdField;
            }
            set {
                if ((this.EducationLevelIdField.Equals(value) != true)) {
                    this.EducationLevelIdField = value;
                    this.RaisePropertyChanged("EducationLevelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HiringYear {
            get {
                return this.HiringYearField;
            }
            set {
                if ((this.HiringYearField.Equals(value) != true)) {
                    this.HiringYearField = value;
                    this.RaisePropertyChanged("HiringYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Post {
            get {
                return this.PostField;
            }
            set {
                if ((object.ReferenceEquals(this.PostField, value) != true)) {
                    this.PostField = value;
                    this.RaisePropertyChanged("Post");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PostLevelId {
            get {
                return this.PostLevelIdField;
            }
            set {
                if ((this.PostLevelIdField.Equals(value) != true)) {
                    this.PostLevelIdField = value;
                    this.RaisePropertyChanged("PostLevelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StartPostYear {
            get {
                return this.StartPostYearField;
            }
            set {
                if ((this.StartPostYearField.Equals(value) != true)) {
                    this.StartPostYearField = value;
                    this.RaisePropertyChanged("StartPostYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SummaryId {
            get {
                return this.SummaryIdField;
            }
            set {
                if ((this.SummaryIdField.Equals(value) != true)) {
                    this.SummaryIdField = value;
                    this.RaisePropertyChanged("SummaryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool WasQualificationIncrease {
            get {
                return this.WasQualificationIncreaseField;
            }
            set {
                if ((this.WasQualificationIncreaseField.Equals(value) != true)) {
                    this.WasQualificationIncreaseField = value;
                    this.RaisePropertyChanged("WasQualificationIncrease");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool WasValidate {
            get {
                return this.WasValidateField;
            }
            set {
                if ((this.WasValidateField.Equals(value) != true)) {
                    this.WasValidateField = value;
                    this.RaisePropertyChanged("WasValidate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal YearSalary {
            get {
                return this.YearSalaryField;
            }
            set {
                if ((this.YearSalaryField.Equals(value) != true)) {
                    this.YearSalaryField = value;
                    this.RaisePropertyChanged("YearSalary");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EnterpriseServiceReference.EnterpriseDataService")]
    public interface EnterpriseDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnterpriseDataService/GetSummaries", ReplyAction="http://tempuri.org/EnterpriseDataService/GetSummariesResponse")]
        MinStat.Enterprises.WebUI.EnterpriseServiceReference.Summary[] GetSummaries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnterpriseDataService/CreateSummary", ReplyAction="http://tempuri.org/EnterpriseDataService/CreateSummaryResponse")]
        void CreateSummary(string title, int[] activitiesIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnterpriseDataService/CopySummary", ReplyAction="http://tempuri.org/EnterpriseDataService/CopySummaryResponse")]
        void CopySummary(string title, int summaryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnterpriseDataService/RemoveSummary", ReplyAction="http://tempuri.org/EnterpriseDataService/RemoveSummaryResponse")]
        void RemoveSummary(int summaryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnterpriseDataService/UpdateSummary", ReplyAction="http://tempuri.org/EnterpriseDataService/UpdateSummaryResponse")]
        void UpdateSummary(int summaryId, string title, int[] activitiesIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnterpriseDataService/AddActivities", ReplyAction="http://tempuri.org/EnterpriseDataService/AddActivitiesResponse")]
        void AddActivities(int summaryId, int[] activitiesIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnterpriseDataService/RemoveActivity", ReplyAction="http://tempuri.org/EnterpriseDataService/RemoveActivityResponse")]
        void RemoveActivity(int summaryId, int activitiId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnterpriseDataService/GetPeoplesArraySize", ReplyAction="http://tempuri.org/EnterpriseDataService/GetPeoplesArraySizeResponse")]
        int GetPeoplesArraySize(int summaryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnterpriseDataService/GetPeoples", ReplyAction="http://tempuri.org/EnterpriseDataService/GetPeoplesResponse")]
        MinStat.Enterprises.WebUI.EnterpriseServiceReference.Person[] GetPeoples(int summaryId, int size, int offset);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnterpriseDataService/CreatePerson", ReplyAction="http://tempuri.org/EnterpriseDataService/CreatePersonResponse")]
        void CreatePerson(int summaryId, int activityId, string title, string post, int postLevelId, int educationLevelId, decimal yearSalary, bool gender, bool wasQualificationIncrease, bool wasValidate, int birthYear, int hiringYear, int startPostYear, int dismissalYear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnterpriseDataService/UpdatePerson", ReplyAction="http://tempuri.org/EnterpriseDataService/UpdatePersonResponse")]
        void UpdatePerson(int personId, string title, string post, int postLevelId, int educationLevelId, decimal yearSalary, bool gender, bool wasQualificationIncrease, bool wasValidate, int birthYear, int hiringYear, int startPostYear, int dismissalYear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnterpriseDataService/RemovePerson", ReplyAction="http://tempuri.org/EnterpriseDataService/RemovePersonResponse")]
        void RemovePerson(int personId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnterpriseDataService/GetActivities", ReplyAction="http://tempuri.org/EnterpriseDataService/GetActivitiesResponse")]
        MinStat.Enterprises.WebUI.EnterpriseServiceReference.Activity[] GetActivities();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnterpriseDataService/GetActivitiesBySummary", ReplyAction="http://tempuri.org/EnterpriseDataService/GetActivitiesBySummaryResponse")]
        MinStat.Enterprises.WebUI.EnterpriseServiceReference.Activity[] GetActivitiesBySummary(int summaryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnterpriseDataService/PublishSummary", ReplyAction="http://tempuri.org/EnterpriseDataService/PublishSummaryResponse")]
        void PublishSummary(int summaryId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EnterpriseDataServiceChannel : MinStat.Enterprises.WebUI.EnterpriseServiceReference.EnterpriseDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EnterpriseDataServiceClient : System.ServiceModel.ClientBase<MinStat.Enterprises.WebUI.EnterpriseServiceReference.EnterpriseDataService>, MinStat.Enterprises.WebUI.EnterpriseServiceReference.EnterpriseDataService {
        
        public EnterpriseDataServiceClient() {
        }
        
        public EnterpriseDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EnterpriseDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EnterpriseDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EnterpriseDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MinStat.Enterprises.WebUI.EnterpriseServiceReference.Summary[] GetSummaries() {
            return base.Channel.GetSummaries();
        }
        
        public void CreateSummary(string title, int[] activitiesIds) {
            base.Channel.CreateSummary(title, activitiesIds);
        }
        
        public void CopySummary(string title, int summaryId) {
            base.Channel.CopySummary(title, summaryId);
        }
        
        public void RemoveSummary(int summaryId) {
            base.Channel.RemoveSummary(summaryId);
        }
        
        public void UpdateSummary(int summaryId, string title, int[] activitiesIds) {
            base.Channel.UpdateSummary(summaryId, title, activitiesIds);
        }
        
        public void AddActivities(int summaryId, int[] activitiesIds) {
            base.Channel.AddActivities(summaryId, activitiesIds);
        }
        
        public void RemoveActivity(int summaryId, int activitiId) {
            base.Channel.RemoveActivity(summaryId, activitiId);
        }
        
        public int GetPeoplesArraySize(int summaryId) {
            return base.Channel.GetPeoplesArraySize(summaryId);
        }
        
        public MinStat.Enterprises.WebUI.EnterpriseServiceReference.Person[] GetPeoples(int summaryId, int size, int offset) {
            return base.Channel.GetPeoples(summaryId, size, offset);
        }
        
        public void CreatePerson(int summaryId, int activityId, string title, string post, int postLevelId, int educationLevelId, decimal yearSalary, bool gender, bool wasQualificationIncrease, bool wasValidate, int birthYear, int hiringYear, int startPostYear, int dismissalYear) {
            base.Channel.CreatePerson(summaryId, activityId, title, post, postLevelId, educationLevelId, yearSalary, gender, wasQualificationIncrease, wasValidate, birthYear, hiringYear, startPostYear, dismissalYear);
        }
        
        public void UpdatePerson(int personId, string title, string post, int postLevelId, int educationLevelId, decimal yearSalary, bool gender, bool wasQualificationIncrease, bool wasValidate, int birthYear, int hiringYear, int startPostYear, int dismissalYear) {
            base.Channel.UpdatePerson(personId, title, post, postLevelId, educationLevelId, yearSalary, gender, wasQualificationIncrease, wasValidate, birthYear, hiringYear, startPostYear, dismissalYear);
        }
        
        public void RemovePerson(int personId) {
            base.Channel.RemovePerson(personId);
        }
        
        public MinStat.Enterprises.WebUI.EnterpriseServiceReference.Activity[] GetActivities() {
            return base.Channel.GetActivities();
        }
        
        public MinStat.Enterprises.WebUI.EnterpriseServiceReference.Activity[] GetActivitiesBySummary(int summaryId) {
            return base.Channel.GetActivitiesBySummary(summaryId);
        }
        
        public void PublishSummary(int summaryId) {
            base.Channel.PublishSummary(summaryId);
        }
    }
}
